version: '3.1'

services:

  phpbnl_conf_wordpress:
    build: containers/wp-cli
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: phpbnl_conf_db
      WORDPRESS_DB_USER: phpbnl_conf
      WORDPRESS_DB_PASSWORD: c0nf3r3n<3
      WORDPRESS_DB_NAME: phpbnl_conf
      WP_CLI_CONFIG_PATH: /etc/wp/conference.yml
      COMPOSER_ALLOW_SUPERUSER: 1
      COMPOSER_CACHE_DIR: /tmp
    volumes:
      - ./etc/wp:/etc/wp
      - ./www:/var/www/html

  phpbnl_conf_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: phpbnl_conf
      MYSQL_USER: phpbnl_conf
      MYSQL_PASSWORD: c0nf3r3n<3
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
